Don’t need alt versions - fix error in commands
Not sure if this changed (since I copied most of these configs), but running now gives me errors. This commit makes them go away. 

Error: Cask 'brew-cask' is unavailable: '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask/Casks/brew-cask.rb' does not exist.